import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProvider from './provider';

import Footer from '@/components/footer/page';
import Header from '@/components/header/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='w-[375px] min-w-[375px] h-[812px] mx-auto border-2 '>
      <body className={inter.className}>
        {/* <Header /> */}
        <QueryProvider>{children} </QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
